### ISSUE TITLE
[Request] Attacknet Validators

### ISSUE THREAD

**Issue by taxmeifyoucan** [ethereum/public-attacknets#14]
# [Request] Attacknet Validators

* __Project name__: BordelHackerspace
* __Attack name__: `mc_attack_0`
* __Number of validators__: 7
* __Purpose__: ETH2.0 hacking session in Bordel Hackerspace
* __Address__: 0xD0Ed0acb335E4fb02dF3bE93396d162E0F1eC5a3

**Comment by djrtwo** [comment]
Added a note that this is for `mc-attack-0`

**Comment by djrtwo** [comment]
You've received 7 testnet deposit tokens for the `mc_attack_0` testnet
https://goerli.etherscan.io/tx/0xb00bf3fbbf7f888357522dbac299b55a0a80ff222c9b27f4642581f2f532ad5b

You can now submit 7 deposits from the address provided. Note that any goerli eth sent along with the deposit will be returned
